# Generated by Django 2.0.13 on 2019-07-23 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('is_active', models.BooleanField(default=True, help_text='select if this record is currently active')),
                ('name', models.CharField(help_text='type of asset identification', max_length=128, unique=True)),
                ('description', models.CharField(blank=True, help_text='asset ID type description', max_length=255, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('is_active', models.BooleanField(default=True, help_text='select if this record is currently active')),
                ('hostname', models.CharField(help_text='name of host', max_length=255, unique=True)),
                ('asset_id', models.CharField(blank=True, help_text='unique identifier of the asset using this hostname', max_length=255, null=True, unique=True)),
                ('is_assigned', models.BooleanField(default=False, help_text='set to True when hostname is assigned')),
                ('is_eternal', models.BooleanField(default=True, help_text='select if this hostname can be not reassigned or deleted')),
                ('is_reserved', models.BooleanField(default=False, help_text='select if this hostname is reserved, but not assigned')),
                ('reservation_expires', models.DateTimeField(blank=True, help_text='time when this reservation expires', null=True)),
                ('assignment_expires', models.DateTimeField(blank=True, help_text='time when this assignment expires', null=True)),
                ('asset_id_type', models.ForeignKey(blank=True, help_text='type of asset ID used', null=True, on_delete=django.db.models.deletion.CASCADE, to='hostmgr.AssetIdType')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostnamePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('is_active', models.BooleanField(default=True, help_text='select if this record is currently active')),
                ('name', models.CharField(blank=True, help_text='name/reference for this hostname pattern', max_length=16, null=True)),
                ('description', models.CharField(blank=True, help_text='description for this pattern', max_length=255, null=True)),
                ('prefix', models.CharField(help_text='prefix for this hostname patter', max_length=32, unique=True)),
                ('delimiter', models.CharField(blank=True, default='', help_text='delimiter separating prefix to humber', max_length=8, null=True)),
                ('max_hosts', models.IntegerField(default=1000, help_text='maximum number of hosts for this pattern')),
                ('increment', models.IntegerField(default=1, help_text='increment (integer) in to increment hostnames by')),
                ('start_from', models.IntegerField(default=1, help_text='number in to start hostnames at')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('is_active', models.BooleanField(default=True, help_text='select if this record is currently active')),
                ('name', models.CharField(help_text='name of this group', max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, help_text='group email alias for group', max_length=254, null=True)),
                ('group', models.ForeignKey(help_text='group that owns this', on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time when this row was updated')),
                ('is_active', models.BooleanField(default=True, help_text='select if this record is currently active')),
                ('name', models.CharField(help_text='name of this project', max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text='description of this project', max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmgr.Owner')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='hostnamepattern',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostmgr.Project'),
        ),
    ]
