# Generated by Django 2.0.13 on 2019-07-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='asset_id',
            field=models.CharField(blank=True, help_text='unique identifier of the asset using this hostname', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hostnamepattern',
            name='max_hosts',
            field=models.IntegerField(default=100, help_text='maximum number of hosts for this pattern'),
        ),
    ]
