# Generated by Django 2.0.13 on 2019-08-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostmgr', '0002_auto_20190813_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pattern',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='pattern',
            unique_together={('prefix', 'delimiter')},
        ),
    ]
