# Generated by Django 2.0.13 on 2019-08-01 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostmgr', '0002_auto_20190724_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostname',
            name='pattern',
            field=models.ForeignKey(default=1, help_text='pattern this hostname was generated from', on_delete=django.db.models.deletion.CASCADE, to='hostmgr.HostnamePattern'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostname',
            name='is_eternal',
            field=models.BooleanField(default=False, help_text='select if hostname can be not reassigned or deleted'),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='is_reserved',
            field=models.BooleanField(default=False, help_text='select if hostname is reserved, but not assigned'),
        ),
        migrations.AlterField(
            model_name='hostnamepattern',
            name='prefix',
            field=models.CharField(help_text='prefix for this hostname patter', max_length=32),
        ),
        migrations.AlterField(
            model_name='owner',
            name='group',
            field=models.ForeignKey(help_text='group this owner belongs to', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
