# Generated by Django 2.0.13 on 2019-08-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostmgr', '0003_auto_20190813_1553'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pattern',
            unique_together={('project', 'prefix', 'delimiter')},
        ),
    ]
