# Generated by Django 2.0.13 on 2019-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmgr', '0003_auto_20190801_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostname',
            name='is_assigned',
        ),
        migrations.RemoveField(
            model_name='hostname',
            name='is_reserved',
        ),
        migrations.AddField(
            model_name='hostname',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('assigned', 'assigned'), ('reserved', 'reserved'), ('expired', 'expired')], default='available', help_text='status of this hostname', max_length=16),
        ),
    ]
