# Generated by Django 2.0.13 on 2019-08-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmgr', '0004_auto_20190813_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='delimiter',
            new_name='prefix_delimiter',
        ),
        migrations.AddField(
            model_name='pattern',
            name='suffix',
            field=models.CharField(blank=True, help_text='suffix for this hostname pattern', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='suffix_delimiter',
            field=models.CharField(blank=True, default='', help_text='character(s) separating number and suffix', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('assigned', 'assigned'), ('reserved', 'reserved'), ('expired', 'expired'), ('unavailable', 'unavailable')], default='available', help_text='status of this hostname', max_length=16),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='prefix',
            field=models.CharField(help_text='prefix for this hostname pattern', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='pattern',
            unique_together={('prefix', 'prefix_delimiter', 'suffix', 'suffix_delimiter')},
        ),
    ]
