# Generated by Django 2.0.13 on 2019-08-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmgr', '0005_auto_20190820_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(blank=True, help_text='name/reference for this hostname pattern', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='prefix',
            field=models.CharField(blank=True, help_text='prefix for this hostname pattern', max_length=32, null=True),
        ),
    ]
