# Generated by Django 2.0.13 on 2019-08-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostmgr', '0006_auto_20190820_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostname',
            name='host_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
